name: 'Action in Action'
description: 'Runs a specified action with pre and post steps'

inputs:
  action:
    description: 'The action to run'
    required: true
  pre:
    description: 'The pre-step to run'
    required: false
  post:
    description: 'The post-step to run'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Pre Step
      if: ${{ inputs.pre != '' }}
      shell: bash
      run: ${{ inputs.pre }}

    - name: Run Specified Action
      shell: bash
      run: |
        # Running ${{ inputs.action }}...
        echo "action_to_run=${{ inputs.action }}" >> $GITHUB_OUTPUT
        echo $action_to_run

    - name: Post Step
      if: ${{ inputs.post != '' }}
      shell: bash
      run: ${{ inputs.post }}
